spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
openapi:
  service:
    api-docs: account-service
    server: http://localhost:${server.port}
    title: Account service
    version: 1.0.0