spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA_NAME:authentication_schema}
    username: ${DATABASE_USERNAME:authentication_user}
    password: ${DATABASE_PASSWORD:authenticationpassword}
    hikari:
      pool-name: HikariConnPool
      maximum-pool-size: 10         # default: 10
      minimum-idle: 10              # default: same as max pool size
      connection-timeout: 30000     # default: 30s
      idle-timeout: 600000          # default: 10 minutes
      max-lifetime: 1800000         # default: 30 minutes
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          min-idle: 0
          max-idle: 8
  cache:
    type: redis

jwt:
  expiryMinutes: 60
  expiryDay: 14
  accessKey: IIwLeRIVsznVTPFEYmA6HiVVBrlKkKqC36OpWzqw8mk=
  refreshKey: tvszknimPZQEdy3c9TCERBLAkOyoCc2ZvOmGcHsRJgg=

openapi:
  service:
    api-docs: authentication-service
    server: http://localhost:${server.port}
    title: Authentication service
    version: 1.0.0