spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DB:haimuoi2-monggo}
  kafka:
    bootstrap-servers: localhost:29092
    topic: checkout-order-topic

stripe:
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}


api:
  internal:
    paymentUrl: ${PAYMENT_SERVICE_URL:http://localhost:8086}
    saleOrderUrl: ${SALE_ORDER_SERVICE:http://localhost:8087/sale-order}
    accountUrl: ${ACCOUNT_SERVICE_URL:http://localhost:8082}

openapi:
  service:
    api-docs: order-service
    server: http://localhost:${server.port}
    title: Order service
    version: 1.0.0