server:
  port: 8085

spring:
  application:
    name: order-service
  profiles:
    active: @spring.profiles.active@

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO
    org:
      apache:
        kafka: OFF