spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: ""  # Password for connecting to the Redis server (default is empty)
      database: 0 # Redis database number
      lettuce:
        pool: # Connection pool settings
          max-active: 8 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 8 # Maximum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms # Maximum wait time to get a connection from the pool (uses -1 for no limit)
      connect-timeout: 30000 # Connection timeout (in milliseconds)
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    properties:
      specific:
        avro:
          reader: true
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme


kafka:
  topic: product-sync-events
# Redisson configuration
redisson:
  connection-pool-size: 50 # Maximum number of connections in the pool
  connection-minimum-idle-size: 10 # Minimum number of idle connections
  idle-connection-timeout: 10000 # Idle connection timeout in milliseconds
  connect-timeout: 10000 # Connection timeout in milliseconds
  timeout: 3000 # Command timeout in milliseconds
  retry-attempts: 3 # Number of retry attempts
  retry-interval: 1500 # Retry interval in milliseconds


openapi:
  service:
    api-docs: product-service
    server: http://localhost:${server.port}
    title: Product service
    version: 1.0.0