spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: 127.0.0.1 # Host of the Redis server
      port: 6319 # Port of the Redis server for connection
      password: ""  # Password for connecting to the Redis server (default is empty)
      database: 1 # Use different database for tests
      lettuce:
        pool: # Connection pool settings
          max-active: 8 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 8 # Maximum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms # Maximum wait time to get a connection from the pool (uses -1 for no limit)
      connect-timeout: 30000 # Connection timeout (in milliseconds)

# Redisson configuration for tests
redisson:
  connection-pool-size: 10 # Smaller pool for tests
  connection-minimum-idle-size: 2 # Minimum number of idle connections
  idle-connection-timeout: 10000 # Idle connection timeout in milliseconds
  connect-timeout: 10000 # Connection timeout in milliseconds
  timeout: 3000 # Command timeout in milliseconds
  retry-attempts: 3 # Number of retry attempts
  retry-interval: 1500 # Retry interval in milliseconds

elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: changeme

openapi:
  service:
    api-docs: product-service
    server: http://localhost:${server.port}
    title: Product service
    version: 1.0.0
