spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    consumer:
      topic-name-send-email-register-topic: send-email-register-topic
      topic-name-send-email-remind-pay-installment: semd-email-remind-pay-installment
  sendgrid:
    api-key: ${SENDGRID_KEY}
    template-id: ${SENDGRID_TEMPLATE}

openapi:
  service:
    api-docs: mail-service
    server: http://localhost:${server.port}
    title: Mail service
    version: 1.0.0