spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers: ${KAFKA_SERVER:localhost:29092}
    updateOrderStatus: update-order-status-topic

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

openapi:
  service:
    api-docs: payment-service
    server: http://localhost:${server.port}
    title: PaymentHistory service
    version: 1.0.0