spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_51RgdzuKbhtqlylb8BpNaIj7n5nPtrN5izUT3MfhvGUaeWdLCZlrlLuV63hZvJOx3lk8BKrhJpJk9gfrVnPHTdORE00Nt6ZAf1Q}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_51RgdzuKbhtqlylb8P180zqt0t3srdjFNXpXor3sFX9i4DngNvh9yW9qbV8t0Nvf6JpapxC07xDfHvE05ddd0L3k90077C2F8Tb}

openapi:
  service:
    api-docs: payment-service
    server: http://localhost:${server.port}
    title: PaymentHistory service
    version: 1.0.0